### ISSUE TITLE
the koyeb crashed

### ISSUE THREAD

**Issue by verzide-pixel** [zchoolzboringzz/interstellarwebsitesecret#1]
😭
![Screenshot 2024-11-05 8 27 18 AM](https://github.com/user-attachments/assets/c94fe7a7-fbff-494a-b9d7-bf2c922c8d8e)

**Comment by zchoolzboringzz** [comment]
updating it right now 👍

**Comment by zchoolzboringzz** [comment]
the link has been updated.

**Comment by verzide-pixel** [comment]
thx
